Use up-to-date versions

diff --git a/rootfs/bin/diskim b/rootfs/bin/diskim
--- a/rootfs/bin/diskim
+++ b/rootfs/bin/diskim
@@ -54,7 +54,7 @@ cmd_copy() {
 	export EXTRACT_UNSAFE_SYMLINKS=1
 	for n in $(find /cd -name '[0-9]*' | sort); do
 		log "Untar [$n]..."
-		tar xf $n || die "Untar failed [$n]"
+		tar -o -xf $n || die "Untar failed [$n]"
 	done
 	cd /
 
